### ISSUE TITLE
最初にロードされた部分しかポイントが表示されない

### ISSUE THREAD

**Issue by tacores** [sytkm/PointsintheWishlist#1]
最近のAmazonウィッシュリストは、下にスクロールしていくたびに表示されるアイテムが動的に増えていく仕様になっている。
PointsintheWishlistでポイントが表示されるのは最初にロードされた部分のみで、動的に増えた部分のポイントが表示されない。

**Comment by sytkm** [comment]
0.2.0にアップデートし対応しました。

**Comment by sytkm** [comment]
ちょっとバグが有ったので0.2.1で修正を行っています。

**Comment by tacores** [comment]
ありがとうございます。すごく便利になりました。
